version: '3.8'

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    container_name: anvil
    restart: unless-stopped
    entrypoint: ["/state/entrypoint.sh"]
    volumes:
      - ./docker/anvil/data:/state
      - ./docker/anvil/entrypoint.sh:/state/entrypoint.sh:ro
    ports:
      - "8545:8545"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "cast block-number --rpc-url http://localhost:8545 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s

  golang:
    build:
      context: .
      dockerfile: Dockerfile
    image: arfanxn/credchain-golang:latest
    container_name: golang
    restart: unless-stopped
    volumes:
      - ./.env.docker:/app/.env:ro
      - ./logs:/app/logs
      - ./docker/backups:/backups
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      anvil:
        condition: service_healthy
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/api/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      golang:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TZ: Asia/Jakarta
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-credchain} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-root}
    volumes:
      - ./docker/mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${MONGO_INITDB_ROOT_USERNAME:-root}", "--password", "${MONGO_INITDB_ROOT_PASSWORD:-root}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  frontend:
  backend:
    external: true